name: Python Checks

on:
  push:
    paths:
      - 'python/**'
  pull_request:
    paths:
      - 'python/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
   
      - name: Run uvx lint
        working-directory: ./python
        run: uvx lint .
        
      - name: Run ruff format check
        working-directory: ./python
        run: uvx ruff format --check .
        
      - name: Run ruff lint
        working-directory: ./python
        run: uvx ruff check .
